# 액션의 이름이다.
name: CI

# 언제 액션이 이루어질 지 정할 수 있다. 아래에 브랜치를 지정해주면 된다.
# 우리는 deploy 브랜치에 Push되면 자동 배포하도록 정의할 것이다.
on:
  push:
    branches: [ deploy-action ]
#  pull_request:
#    branches: [ master ]

# 아래의 Job들이 깃헙 액션에서 진행된다.
jobs:
  # 하나의 Job을 정의한다. 여기서 Job의 이름은 build이다.
  deploy:
    name: DEPLOY
      # 빌드가 어느 운영체제에서 돌아가느냐?
    runs-on: ubuntu-18.04
    env:
      working-directory: ./BE

      # step은 job의 하위 집합이다. step에서 정의한 작업을 순차적으로 진행한다.
    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0
        
        # 위에서 정의한 브랜치로 체크아웃한다.
      - name: Checkout
        uses: actions/checkout@v2

        # 메시지를 출력한다.
      - name: Run a one-line script
        run: echo Start Deploy.

        # 여러 가지의 메시지를 출력할 수 있다.
      - name: Run a multi-line script
        run: |
          echo We love Honux,
          echo CodeSquad 2020 Java Backend.
          
        # 자바 버전을 설정해준다.
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

        # Gradle에 실행 권한을 부여한다.
      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
        shell: bash

        # Gradle을 활용해 배포한다.
      - name: Build with Gradle
        run: |
          echo $(ls)
          ./gradlew build
        shell: bash

        # 버전마다 이름을 다르게 하기 위해서 GITHUB_SHA라고 하는 해시이름을 활용하여 zip 파일을 만든다.
        # CodeDeploy를 사용하기 위해서는 S3를 거쳐야 한다. 따라서 압축된 파일을 만들어주고 이를 옮긴다.
      - name: Make zip file
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

        # AWS 서비스를 사용하기 위한 인증 과정이다.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: service-deploy-user
          aws-secret-access-key: AKIA2LU4OVCKRHWJP5OKNtrjjxD32oNxnHUciC6ATTkRH83UAGAWcGlNoDww
          aws-region: ap-northeast-2

        # 배포 zip 파일을 S3에 업로드한다.
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://isntyet-deploy/$PROJECT_NAME/$GITHUB_SHA.zip

        # 실제로 코드를 배포한다.
      - name: Code Deploy
        run: aws deploy create-deployment --application-name testapp --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=isntyet-deploy,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
